export const COLOR_BLACK = '#000000'
export const COLOR_WHITE = '#ffffff'
export const COLOR_COOL_BLACK = '#00315C'
export const COLOR_CULTURED = '#f4f4f4'
export const COLOR_AMERICAN_ORANGE = '#ff8900'
